// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `download_slots`, `http_client`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// GET 请求，官方优先 + MCIM/CDN 镜像回退。
///
/// 语义与旧 Dart `McimFallbackHttp.get` 一致：任一候选 2xx 即返回；
/// 全部非 2xx 时返回最后一个响应；全部网络错误才抛异常。
Future<McimHttpResponse> mcimGet(
        {required String url,
        Map<String, String>? headers,
        required BigInt timeoutSecs}) =>
    RustLib.instance.api.crateApiMcimFallbackApiMcimGet(
        url: url, headers: headers, timeoutSecs: timeoutSecs);

/// 下载字节（图标等），官方 + 镜像回退，全局 8 并发闸门。
/// 任一候选 2xx 且内容非空即成功；否则全部尝试完后抛异常。
Future<Uint8List> mcimGetBytes(
        {required String url,
        Map<String, String>? headers,
        required BigInt timeoutSecs}) =>
    RustLib.instance.api.crateApiMcimFallbackApiMcimGetBytes(
        url: url, headers: headers, timeoutSecs: timeoutSecs);

class McimHttpResponse {
  final int statusCode;
  final Uint8List body;

  /// 保留响应头（Dart 侧 `http.Response.bytes` 需要 content-type 来解码 JSON）。
  final Map<String, String> headers;

  const McimHttpResponse({
    required this.statusCode,
    required this.body,
    required this.headers,
  });

  @override
  int get hashCode => statusCode.hashCode ^ body.hashCode ^ headers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is McimHttpResponse &&
          runtimeType == other.runtimeType &&
          statusCode == other.statusCode &&
          body == other.body &&
          headers == other.headers;
}
