// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

Future<List<ProjectI18nDto>> getProjectI18N(
        {required List<ProjectI18nKeyDto> keys}) =>
    RustLib.instance.api.crateApiProjectI18NGetProjectI18N(keys: keys);

Future<void> upsertProjectI18N({required List<ProjectI18nUpsertDto> rows}) =>
    RustLib.instance.api.crateApiProjectI18NUpsertProjectI18N(rows: rows);

Future<String> textI18NHash(
        {String? platform,
        String? projectId,
        required String kind,
        required String sourceText}) =>
    RustLib.instance.api.crateApiProjectI18NTextI18NHash(
        platform: platform,
        projectId: projectId,
        kind: kind,
        sourceText: sourceText);

Future<TextI18nDto?> getTextI18N({required String contentHash}) =>
    RustLib.instance.api
        .crateApiProjectI18NGetTextI18N(contentHash: contentHash);

Future<void> upsertTextI18N(
        {required String contentHash,
        String? platform,
        String? projectId,
        required String kind,
        required String sourceText,
        required String zhText,
        required String provider}) =>
    RustLib.instance.api.crateApiProjectI18NUpsertTextI18N(
        contentHash: contentHash,
        platform: platform,
        projectId: projectId,
        kind: kind,
        sourceText: sourceText,
        zhText: zhText,
        provider: provider);

/// Aggregate persistent translation cache stats for settings UI.
Future<TranslationCacheStatsDto> translationCacheStats() =>
    RustLib.instance.api.crateApiProjectI18NTranslationCacheStats();

Future<PlatformInt64> clearProjectI18NCache() =>
    RustLib.instance.api.crateApiProjectI18NClearProjectI18NCache();

Future<PlatformInt64> clearTextI18NCache() =>
    RustLib.instance.api.crateApiProjectI18NClearTextI18NCache();

/// Clear project titles/summaries and body cache.
Future<PlatformInt64> clearAllTranslationCaches() =>
    RustLib.instance.api.crateApiProjectI18NClearAllTranslationCaches();

class ProjectI18nDto {
  final String platform;
  final String projectId;
  final String? slug;
  final String sourceTitle;
  final String? zhTitle;
  final String? sourceSummary;
  final String? zhSummary;
  final String? titleProvider;
  final String? summaryProvider;
  final double titleConfidence;
  final double summaryConfidence;
  final String status;
  final PlatformInt64 hitCount;
  final String lastSeenAt;
  final String updatedAt;

  const ProjectI18nDto({
    required this.platform,
    required this.projectId,
    this.slug,
    required this.sourceTitle,
    this.zhTitle,
    this.sourceSummary,
    this.zhSummary,
    this.titleProvider,
    this.summaryProvider,
    required this.titleConfidence,
    required this.summaryConfidence,
    required this.status,
    required this.hitCount,
    required this.lastSeenAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      platform.hashCode ^
      projectId.hashCode ^
      slug.hashCode ^
      sourceTitle.hashCode ^
      zhTitle.hashCode ^
      sourceSummary.hashCode ^
      zhSummary.hashCode ^
      titleProvider.hashCode ^
      summaryProvider.hashCode ^
      titleConfidence.hashCode ^
      summaryConfidence.hashCode ^
      status.hashCode ^
      hitCount.hashCode ^
      lastSeenAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectI18nDto &&
          runtimeType == other.runtimeType &&
          platform == other.platform &&
          projectId == other.projectId &&
          slug == other.slug &&
          sourceTitle == other.sourceTitle &&
          zhTitle == other.zhTitle &&
          sourceSummary == other.sourceSummary &&
          zhSummary == other.zhSummary &&
          titleProvider == other.titleProvider &&
          summaryProvider == other.summaryProvider &&
          titleConfidence == other.titleConfidence &&
          summaryConfidence == other.summaryConfidence &&
          status == other.status &&
          hitCount == other.hitCount &&
          lastSeenAt == other.lastSeenAt &&
          updatedAt == other.updatedAt;
}

class ProjectI18nKeyDto {
  final String platform;
  final String projectId;

  const ProjectI18nKeyDto({
    required this.platform,
    required this.projectId,
  });

  @override
  int get hashCode => platform.hashCode ^ projectId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectI18nKeyDto &&
          runtimeType == other.runtimeType &&
          platform == other.platform &&
          projectId == other.projectId;
}

class ProjectI18nUpsertDto {
  final String platform;
  final String projectId;
  final String? slug;
  final String sourceTitle;
  final String? zhTitle;
  final String? sourceSummary;
  final String? zhSummary;
  final String? titleProvider;
  final String? summaryProvider;
  final double? titleConfidence;
  final double? summaryConfidence;
  final String? status;

  const ProjectI18nUpsertDto({
    required this.platform,
    required this.projectId,
    this.slug,
    required this.sourceTitle,
    this.zhTitle,
    this.sourceSummary,
    this.zhSummary,
    this.titleProvider,
    this.summaryProvider,
    this.titleConfidence,
    this.summaryConfidence,
    this.status,
  });

  @override
  int get hashCode =>
      platform.hashCode ^
      projectId.hashCode ^
      slug.hashCode ^
      sourceTitle.hashCode ^
      zhTitle.hashCode ^
      sourceSummary.hashCode ^
      zhSummary.hashCode ^
      titleProvider.hashCode ^
      summaryProvider.hashCode ^
      titleConfidence.hashCode ^
      summaryConfidence.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectI18nUpsertDto &&
          runtimeType == other.runtimeType &&
          platform == other.platform &&
          projectId == other.projectId &&
          slug == other.slug &&
          sourceTitle == other.sourceTitle &&
          zhTitle == other.zhTitle &&
          sourceSummary == other.sourceSummary &&
          zhSummary == other.zhSummary &&
          titleProvider == other.titleProvider &&
          summaryProvider == other.summaryProvider &&
          titleConfidence == other.titleConfidence &&
          summaryConfidence == other.summaryConfidence &&
          status == other.status;
}

class TextI18nDto {
  final String contentHash;
  final String? platform;
  final String? projectId;
  final String kind;
  final String sourceText;
  final String zhText;
  final String provider;
  final String updatedAt;

  const TextI18nDto({
    required this.contentHash,
    this.platform,
    this.projectId,
    required this.kind,
    required this.sourceText,
    required this.zhText,
    required this.provider,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      contentHash.hashCode ^
      platform.hashCode ^
      projectId.hashCode ^
      kind.hashCode ^
      sourceText.hashCode ^
      zhText.hashCode ^
      provider.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextI18nDto &&
          runtimeType == other.runtimeType &&
          contentHash == other.contentHash &&
          platform == other.platform &&
          projectId == other.projectId &&
          kind == other.kind &&
          sourceText == other.sourceText &&
          zhText == other.zhText &&
          provider == other.provider &&
          updatedAt == other.updatedAt;
}

class TranslationCacheStatsDto {
  final PlatformInt64 projectEntries;
  final PlatformInt64 textEntries;
  final PlatformInt64 totalHits;
  final PlatformInt64 projectBytes;
  final PlatformInt64 textBytes;

  const TranslationCacheStatsDto({
    required this.projectEntries,
    required this.textEntries,
    required this.totalHits,
    required this.projectBytes,
    required this.textBytes,
  });

  Future<PlatformInt64> totalBytes() => RustLib.instance.api
          .crateApiProjectI18NTranslationCacheStatsDtoTotalBytes(
        that: this,
      );

  @override
  int get hashCode =>
      projectEntries.hashCode ^
      textEntries.hashCode ^
      totalHits.hashCode ^
      projectBytes.hashCode ^
      textBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslationCacheStatsDto &&
          runtimeType == other.runtimeType &&
          projectEntries == other.projectEntries &&
          textEntries == other.textEntries &&
          totalHits == other.totalHits &&
          projectBytes == other.projectBytes &&
          textBytes == other.textBytes;
}
