// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `file_len`, `measure_dir`, `measure_instance`, `measure_request`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// 批量测量多个路径（文件或目录）。失败的路径按 (0, 0) 返回。
Future<List<PathMeasureResult>> measurePaths(
        {required List<PathMeasureRequest> requests}) =>
    RustLib.instance.api.crateApiStorageScanMeasurePaths(requests: requests);

/// 批量测量实例目录：单遍扫描，按 mods/resourcepacks/... 分桶，
/// 其余（根下文件 + 未知目录）归入 `other`。
Future<List<InstanceMeasureResult>> measureInstances(
        {required List<String> paths}) =>
    RustLib.instance.api.crateApiStorageScanMeasureInstances(paths: paths);

class InstanceMeasureResult {
  final PlatformInt64 totalBytes;
  final PlatformInt64 totalFiles;
  final List<InstancePartStat> parts;

  const InstanceMeasureResult({
    required this.totalBytes,
    required this.totalFiles,
    required this.parts,
  });

  @override
  int get hashCode =>
      totalBytes.hashCode ^ totalFiles.hashCode ^ parts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstanceMeasureResult &&
          runtimeType == other.runtimeType &&
          totalBytes == other.totalBytes &&
          totalFiles == other.totalFiles &&
          parts == other.parts;
}

/// 实例目录分桶统计的一部分（mods/saves/... 或 other）。
class InstancePartStat {
  final String id;
  final PlatformInt64 bytes;
  final PlatformInt64 fileCount;

  const InstancePartStat({
    required this.id,
    required this.bytes,
    required this.fileCount,
  });

  @override
  int get hashCode => id.hashCode ^ bytes.hashCode ^ fileCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstancePartStat &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bytes == other.bytes &&
          fileCount == other.fileCount;
}

/// 单个路径的测量请求。
class PathMeasureRequest {
  final String path;
  final bool isFile;

  /// 这些名称（小写比较）的顶层子项不计入统计。
  final List<String> excludeChildNames;

  /// 只统计目录根下的普通文件（用于 manifest 清单等）。
  final bool onlyFilesAtRoot;

  const PathMeasureRequest({
    required this.path,
    required this.isFile,
    required this.excludeChildNames,
    required this.onlyFilesAtRoot,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      isFile.hashCode ^
      excludeChildNames.hashCode ^
      onlyFilesAtRoot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PathMeasureRequest &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          isFile == other.isFile &&
          excludeChildNames == other.excludeChildNames &&
          onlyFilesAtRoot == other.onlyFilesAtRoot;
}

class PathMeasureResult {
  final PlatformInt64 bytes;
  final PlatformInt64 fileCount;

  const PathMeasureResult({
    required this.bytes,
    required this.fileCount,
  });

  static Future<PathMeasureResult> default_() =>
      RustLib.instance.api.crateApiStorageScanPathMeasureResultDefault();

  @override
  int get hashCode => bytes.hashCode ^ fileCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PathMeasureResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          fileCount == other.fileCount;
}
